version: '3.8'

services:
  dpr-car-rentals:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dpr-car-rentals-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy if needed
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: dpr-car-rentals-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - dpr-car-rentals
  #   restart: unless-stopped

networks:
  default:
    name: dpr-car-rentals-network