name: dpr_car_rentals
description: "This system is made for our client to help his car business rental more smooth and flexible"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^7.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.7
  shared_preferences: ^2.5.3
  firebase_auth: ^5.4.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.3.0
  flutter_dotenv: ^6.0.0
  intl: ^0.18.0
  email_sender: ^2.1.0
  mailer: ^6.0.0
  google_sign_in: ^7.1.1
  image_picker: ^1.0.4
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.5.0

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_24pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_24pt-Black.ttf
          weight: 900